{
 "title": "Wise.us Pod monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "Deployment",
    "query": "kube_deployment_labels{namespace=\"$namespace\"}"
   },
   { "name": "Daemonset", "query": "label_values(daemonset)" },
   { "name": "Statefulset", "query": "label_values(statefulset)" }
  ]
 },
 "panels": [
  { "title": "Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\",container=\"$Deployment\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",container=\"$Deployment\"}",
     "legendFormat": "limits {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",container=\"$Deployment\"}",
     "legendFormat": "requests {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"$Deployment\",namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{container=\"$Deployment\",namespace=\"$namespace\"}",
     "legendFormat": "Request {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{container=\"$Deployment\",namespace=\"$namespace\"}",
     "legendFormat": "Limits {{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage of all pods in $namespace namespace",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Metrics all pods in $namespace namespace",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{container=\"POD\",namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{container!=\"POD\",namespace=\"$namespace\"}",
     "legendFormat": "Request {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{container!=\"POD\",namespace=\"$namespace\"}",
     "legendFormat": "limits {{pod}}"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_role=\"master\"})",
     "legendFormat": "master "
    },
    {
     "expr": "kube_node_labels{label_role=\"worker\"}",
     "legendFormat": "worker {{ label_failure_domain_beta_kubernetes_io_zone }}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_capacity_cpu_cores",
     "legendFormat": "{{node}}"
    },
    {}
   ]
  }
 ]
}