install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: /home/talentica-all.com/niting/.cache/helm/repository/kubernetes-external-secrets-3.3.0.tgz

NAME: external-secret
LAST DEPLOYED: Sat May 30 16:06:01 2020
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
env:
  AWS_REGION: us-west-2
  GOOGLE_APPLICATION_CREDENTIALS: /app/gcp-creds/gcp-creds.json
  LOG_LEVEL: info
  METRICS_PORT: 3001
  POLLER_INTERVAL_MILLISECONDS: 10000
  VAULT_ADDR: http://127.0.0.1:8200
fullnameOverride: ""
image:
  imagePullSecrets: []
  pullPolicy: IfNotPresent
  repository: godaddy/kubernetes-external-secrets
  tag: 3.3.0
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podLabels: {}
rbac:
  create: true
replicaCount: 1
resources: {}
securityContext:
  runAsNonRoot: true
serviceAccount:
  annotations: {}
  create: true
  name: null
serviceMonitor:
  enabled: false
  interval: 30s
  namespace: null
tolerations: []

HOOKS:
MANIFEST:
---
# Source: kubernetes-external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secret-kubernetes-external-secrets
  namespace: "default"
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-3.3.0
    app.kubernetes.io/instance: external-secret
    app.kubernetes.io/managed-by: Helm
---
# Source: kubernetes-external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-secret-kubernetes-external-secrets
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-3.3.0
    app.kubernetes.io/instance: external-secret
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    resourceNames: ["externalsecrets.kubernetes-client.io"]
    verbs: ["get", "update"]
  - apiGroups: ["kubernetes-client.io"]
    resources: ["externalsecrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["kubernetes-client.io"]
    resources: ["externalsecrets/status"]
    verbs: ["get", "update"]
---
# Source: kubernetes-external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-secret-kubernetes-external-secrets
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-3.3.0
    app.kubernetes.io/instance: external-secret
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secret-kubernetes-external-secrets
subjects:
  - name: external-secret-kubernetes-external-secrets
    namespace: "default"
    kind: ServiceAccount
---
# Source: kubernetes-external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-secret-kubernetes-external-secrets-auth
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-3.3.0
    app.kubernetes.io/instance: external-secret
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- name: external-secret-kubernetes-external-secrets
  namespace: "default"
  kind: ServiceAccount
---
# Source: kubernetes-external-secrets/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: external-secret-kubernetes-external-secrets
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-3.3.0
    app.kubernetes.io/instance: external-secret
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: kubernetes-external-secrets
  ports:
    - protocol: TCP
      port: 3001
      name: prometheus
      targetPort: prometheus
---
# Source: kubernetes-external-secrets/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secret-kubernetes-external-secrets
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-3.3.0
    app.kubernetes.io/instance: external-secret
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-external-secrets
      app.kubernetes.io/instance: external-secret
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubernetes-external-secrets
        app.kubernetes.io/instance: external-secret
    spec:
      serviceAccountName: external-secret-kubernetes-external-secrets
      containers:
        - name: kubernetes-external-secrets
          image: "godaddy/kubernetes-external-secrets:3.3.0"
          ports:
          - name: prometheus
            containerPort: 3001
          imagePullPolicy: IfNotPresent
          resources:
            {}
          env:
          - name: "AWS_REGION"
            value: "us-west-2"
          - name: "GOOGLE_APPLICATION_CREDENTIALS"
            value: "/app/gcp-creds/gcp-creds.json"
          - name: "LOG_LEVEL"
            value: "info"
          - name: "METRICS_PORT"
            value: "3001"
          - name: "POLLER_INTERVAL_MILLISECONDS"
            value: "10000"
          - name: "VAULT_ADDR"
            value: "http://127.0.0.1:8200"
          # Params for env vars populated from k8s secrets
      securityContext:
        runAsNonRoot: true

NOTES:
The kubernetes external secrets has been installed. Check its status by running:
  kubectl --namespace default get pods -l "app.kubernetes.io/name=kubernetes-external-secrets,app.kubernetes.io/instance=external-secret"

Visit https://github.com/godaddy/kubernetes-external-secrets for instructions on how to use kubernetes external secrets

