apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: "default"
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-4.0.0
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm

