apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: k8s-internal 
  app: prometheus
  namespace: monitoring
spec:
  backendType: systemManager
  template:
    type: kubernetes.io/tls
  data:
{{ toYaml .Values.secret.ingress.data | indent 4 }}
